controller_list:
  - name: fake_serpens_arm_controller
    type: $(arg execution_type)
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_serpens_tool_controller
    type: $(arg execution_type)
    joints:
      - joint6
initial:  # Define initial robot poses.
  - group: serpens_arm
    pose: home
  - group: serpens_tool
    pose: end_normal